---

- name: Setup Apache with php in GMT+1 timezone
  hosts: all
  become: true
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Apache on server
      apt:
        name: apache2
        state: present

    - name: Start apache2 service
      service:
        name: apache2
        state: started

    - name: Set timezone
      timezone:
        name: Africa/Lagos

    - name: Copy file with owner and permissions
      become: true
      copy:
        src: /Users/yutee/Desktop/Alt___School/second-semester/altschool-cloud-exercises/exercise9/index.php
        dest: /var/www/html/index.php
        owner: root
        group: root
        mode: 0644

    - name: Restart apache2 service
      service:
        name: apache2
        state: restarted

# Running a script directly on the shell of the host system
#    - name: Run script
#      script: index.sh