---
- name: Install NGINX and deploy website
  hosts: servers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Add nginx configuration
      copy:
        src: website/static-site-config
        dest: /etc/nginx/sites-available/
        owner: root
        group: root
        mode: '0644'

    - name: Enable website configuration
      file:
        src: /etc/nginx/sites-available/static-site-config
        dest: /etc/nginx/sites-enabled/static-site-config
        state: link

    - name: Copy the HTML file to the default NGINX directory
      copy:
        src: website/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure NGINX is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes